//! Parser module — recursive-descent parser for C11 with GCC extensions.
//!
//! This module produces a complete AST from the token stream generated by the
//! lexer. The AST node types are defined in [`ast`].

pub mod ast;
