//! # x86-64 Security Hardening Module
//!
//! This module implements three x86-64-specific security features for the `bcc`
//! C compiler, activated by GCC-compatible command-line flags:
//!
//! ## 1. Retpoline Thunk Generation (`-mretpoline`)
//!
//! Replaces indirect `call *%reg` instructions with calls to speculative-
//! execution-safe "retpoline" thunk sequences, mitigating Spectre v2 / Branch
//! Target Injection (BTI) attacks. Retpoline thunks are generated for registers
//! commonly used in indirect calls: RAX, RCX, RDX, and R11.
//!
//! The canonical retpoline sequence for `%rax`:
//!
//! ```text
//! __x86_retpoline_rax:
//!     call .Lsetup_rax          ; push return address onto stack
//! .Lcapture_spec_rax:
//!     pause                     ; keep speculation loop lightweight
//!     lfence                    ; serialise speculative execution
//!     jmp .Lcapture_spec_rax    ; infinite loop (never actually taken)
//! .Lsetup_rax:
//!     mov %rax, (%rsp)          ; overwrite return address with target
//!     ret                       ; return to actual target, NOT .Lcapture_spec
//! ```
//!
//! ## 2. Intel CET `endbr64` Insertion (`-fcf-protection`)
//!
//! Inserts `endbr64` (End Branch 64-bit) instructions at all function entries
//! and indirect branch targets. This enables Intel's Control-flow Enforcement
//! Technology (CET) Indirect Branch Tracking (IBT), which raises a `#CP`
//! exception if an indirect branch lands on a non-`endbr64` instruction.
//!
//! The `endbr64` instruction encodes as 4 bytes: `F3 0F 1E FA`.
//!
//! ## 3. Automatic Stack Probing (frames > 4096 bytes)
//!
//! Generates page-straddling probe loops for function stack frames that exceed
//! one memory page (4096 bytes). This ensures the OS guard page is hit before
//! any writes to the newly allocated stack space, preventing "stack clash"
//! attacks where an attacker could skip past the guard page with a large
//! allocation.
//!
//! ## Zero External Dependencies
//!
//! This module uses only the Rust standard library (`std`) and internal crate
//! modules. No external crates are imported.

use crate::codegen::{
    CodeGenError, MachineInstr, MachineOperand, Section, SectionFlags, SectionType,
};
use crate::codegen::regalloc::PhysReg;
use crate::codegen::x86_64::abi::{RAX, RCX, RDX, RSP, R11};
use crate::codegen::x86_64::isel::{opcodes, CondCode};

// ============================================================================
// Constants
// ============================================================================

/// Standard page size for stack probing (4096 bytes = one x86 page).
const PAGE_SIZE: u32 = 4096;

/// Maximum number of pages to unroll in stack probing before switching
/// to a loop. Frames up to `PROBE_UNROLL_LIMIT * PAGE_SIZE` bytes generate
/// unrolled probe sequences; larger frames use a counted loop.
const PROBE_UNROLL_LIMIT: u32 = 8;

/// Registers for which retpoline thunks are generated. These are the
/// registers most commonly used for indirect calls/jumps in x86-64 code
/// generated by C compilers.
const RETPOLINE_REGS: [(PhysReg, &str); 4] = [
    (RAX, "rax"),
    (RCX, "rcx"),
    (RDX, "rdx"),
    (R11, "r11"),
];

/// Internal label ID for the stack probe loop back-edge target.
/// Uses a high value unlikely to collide with user-generated labels.
const PROBE_LOOP_LABEL: u32 = 0xFFFF_FF00;

// ============================================================================
// SecurityConfig — configuration for security hardening features
// ============================================================================

/// Configuration controlling which x86-64 security hardening features are
/// enabled for a compilation.
///
/// All fields correspond to GCC-compatible CLI flags. Stack probing is always
/// active with a default threshold of 4096 bytes (one page), while retpoline
/// and CET require explicit opt-in via `-mretpoline` and `-fcf-protection`.
#[derive(Debug, Clone)]
pub struct SecurityConfig {
    /// Enable retpoline thunks for indirect branches (`-mretpoline`).
    ///
    /// When `true`, all indirect `call *%reg` instructions are replaced with
    /// calls to speculative-execution-safe retpoline thunk sequences.
    pub retpoline: bool,

    /// Enable Intel CET `endbr64` insertion (`-fcf-protection`).
    ///
    /// When `true`, `endbr64` instructions are inserted at function entries
    /// and indirect branch targets to support Intel's Indirect Branch Tracking.
    pub cf_protection: bool,

    /// Stack frame size threshold (in bytes) above which stack probing is
    /// emitted. Frames with total size exceeding this value will include
    /// probe sequences that touch every page between the old and new RSP.
    ///
    /// Default: 4096 (one x86 page). This is always active.
    pub stack_probe_threshold: u32,
}

impl Default for SecurityConfig {
    /// Returns a default configuration with all optional features disabled
    /// and the standard stack probe threshold of 4096 bytes.
    fn default() -> Self {
        Self {
            retpoline: false,
            cf_protection: false,
            stack_probe_threshold: PAGE_SIZE,
        }
    }
}

impl SecurityConfig {
    /// Create a `SecurityConfig` from CLI flag values.
    ///
    /// - `retpoline`: corresponds to the `-mretpoline` flag.
    /// - `cf_protection`: corresponds to the `-fcf-protection` flag.
    ///
    /// Stack probing is always enabled with the default threshold (4096 bytes).
    pub fn from_flags(retpoline: bool, cf_protection: bool) -> Self {
        Self {
            retpoline,
            cf_protection,
            stack_probe_threshold: PAGE_SIZE,
        }
    }
}

// ============================================================================
// RetpolineThunk — a self-contained retpoline code sequence
// ============================================================================

/// A retpoline thunk for a specific register.
///
/// Each thunk is a small self-contained function that replaces an indirect
/// `call *%reg` with a speculative-execution-safe sequence. The thunk's
/// symbol name follows the GCC convention `__x86_retpoline_<reg>`.
///
/// The thunk code is 17 bytes:
/// - `call .Lsetup` (5 bytes: E8 + rel32)
/// - `pause` (2 bytes: F3 90)
/// - `lfence` (3 bytes: 0F AE E8)
/// - `jmp .Lcapture_spec` (2 bytes: EB + rel8)
/// - `mov %reg, (%rsp)` (4 bytes: REX.W 89 ModR/M SIB)
/// - `ret` (1 byte: C3)
#[derive(Debug, Clone)]
pub struct RetpolineThunk {
    /// Symbol name, e.g. `"__x86_retpoline_rax"`.
    pub name: String,

    /// The physical register this thunk handles.
    pub register: PhysReg,

    /// Raw machine code bytes of the thunk sequence (17 bytes).
    pub code: Vec<u8>,
}

// ============================================================================
// SecurityHardening — main entry point for security features
// ============================================================================

/// Main entry point for applying x86-64 security hardening features.
///
/// Instantiate with a [`SecurityConfig`] and call methods to:
/// - Generate retpoline thunks and replace indirect calls
/// - Insert `endbr64` instructions at function entries and indirect targets
/// - Generate stack probing sequences for large frames
/// - Apply all features at once via [`apply_security_hardening`]
pub struct SecurityHardening {
    config: SecurityConfig,
}

impl SecurityHardening {
    /// Create a new `SecurityHardening` instance with the given configuration.
    pub fn new(config: SecurityConfig) -> Self {
        Self { config }
    }

    // ========================================================================
    // Retpoline Thunk Generation (-mretpoline)
    // ========================================================================

    /// Generate retpoline thunks for all commonly-used indirect call registers.
    ///
    /// Returns thunks for RAX, RCX, RDX, and R11. Each thunk is a self-
    /// contained code sequence with a known symbol name that indirect calls
    /// are rewritten to target.
    ///
    /// Returns an empty vector if retpoline is not enabled.
    pub fn generate_retpoline_thunks(&self) -> Vec<RetpolineThunk> {
        if !self.config.retpoline {
            return Vec::new();
        }
        RETPOLINE_REGS
            .iter()
            .map(|&(reg, name)| {
                let thunk_name = format!("__x86_retpoline_{}", name);
                encode_retpoline_thunk(reg, &thunk_name)
            })
            .collect()
    }

    /// Returns `true` if the given instruction is an indirect call through a
    /// register that should be replaced with a retpoline call.
    ///
    /// Currently detects instructions with opcode [`opcodes::CALL_R`]
    /// (indirect call via register) whose first operand is a
    /// [`MachineOperand::Register`].
    pub fn needs_retpoline_replacement(&self, instr: &MachineInstr) -> bool {
        if !self.config.retpoline {
            return false;
        }
        // Detect indirect calls via register: opcode is CALL_R and
        // the first operand is a physical register.
        if instr.opcode == opcodes::CALL_R {
            if let Some(MachineOperand::Register(reg)) = instr.operands.first() {
                // Verify the register has a retpoline thunk available.
                // Access the inner u16 field to validate.
                let _encoding = reg.0;
                return retpoline_thunk_name_for_reg(*reg).is_some();
            }
        }
        false
    }

    /// Replace all indirect `call *%reg` instructions in the given vector
    /// with direct calls to the corresponding retpoline thunk symbol.
    ///
    /// For example, `call *%rax` (CALL_R with Register(RAX)) is replaced
    /// with `call __x86_retpoline_rax` (CALL with Symbol).
    ///
    /// Does nothing if retpoline is not enabled.
    pub fn apply_retpoline(&self, instrs: &mut Vec<MachineInstr>) {
        if !self.config.retpoline {
            return;
        }

        for i in 0..instrs.len() {
            if instrs[i].opcode != opcodes::CALL_R {
                continue;
            }

            // Extract the target register from the indirect call.
            let reg = match instrs[i].operands.first() {
                Some(MachineOperand::Register(r)) => *r,
                _ => continue,
            };

            // Look up the retpoline thunk symbol name for this register.
            if let Some(thunk_name) = retpoline_thunk_name_for_reg(reg) {
                // Preserve the source location from the original instruction
                // so DWARF debug info remains accurate.
                let loc = instrs[i].loc.clone();

                // Replace with a direct call to the retpoline thunk.
                let mut replacement = MachineInstr::with_operands(
                    opcodes::CALL,
                    vec![MachineOperand::Symbol(thunk_name)],
                );
                replacement.loc = loc;
                instrs[i] = replacement;
            }
        }
    }

    // ========================================================================
    // Intel CET endbr64 Insertion (-fcf-protection)
    // ========================================================================

    /// Insert an `endbr64` instruction at the beginning of a function's
    /// machine code byte sequence.
    ///
    /// This marks the function entry as a valid indirect branch target for
    /// Intel CET. The 4-byte `endbr64` encoding (`F3 0F 1E FA`) is prepended
    /// at byte offset 0 of the function's code.
    ///
    /// Does nothing if CF protection is not enabled.
    pub fn insert_endbr64_at_function_entry(&self, code: &mut Vec<u8>) {
        if !self.config.cf_protection {
            return;
        }
        let endbr64_bytes = encode_endbr64();
        // Prepend the 4-byte endbr64 at the very start of the function.
        code.splice(0..0, endbr64_bytes.iter().copied());
    }

    /// Insert `endbr64` machine instructions at basic block entries that
    /// are targets of indirect branches.
    ///
    /// The `labels` parameter contains label IDs (basic block identifiers or
    /// instruction indices) where indirect branches may land. An ENDBR64
    /// [`MachineInstr`] is inserted at each corresponding position.
    ///
    /// Labels are interpreted as instruction indices into the `instrs` vector.
    /// Insertions are performed in reverse order to preserve index validity.
    ///
    /// Does nothing if CF protection is not enabled or `labels` is empty.
    pub fn insert_endbr64_at_indirect_targets(
        &self,
        instrs: &mut Vec<MachineInstr>,
        labels: &[u32],
    ) {
        if !self.config.cf_protection || labels.is_empty() {
            return;
        }

        let endbr64_instr = MachineInstr::with_operands(opcodes::ENDBR64, vec![]);

        // Deduplicate and sort label positions.
        let mut positions: Vec<usize> = labels
            .iter()
            .map(|&l| l as usize)
            .filter(|&idx| idx <= instrs.len())
            .collect();
        positions.sort_unstable();
        positions.dedup();

        // Insert in reverse order so earlier indices remain valid.
        for &pos in positions.iter().rev() {
            instrs.insert(pos, endbr64_instr.clone());
        }
    }

    // ========================================================================
    // Stack Probing for Large Frames
    // ========================================================================

    /// Returns `true` if a function with the given `frame_size` (in bytes)
    /// requires stack probing.
    ///
    /// Stack probing is needed when the frame size exceeds the configured
    /// threshold (default: 4096 bytes = one page).
    pub fn needs_stack_probe(&self, frame_size: u32) -> bool {
        frame_size > self.config.stack_probe_threshold
    }

    /// Generate a stack probe sequence as raw machine code bytes.
    ///
    /// The probe touches every page between the current RSP and the desired
    /// allocation point (`RSP - frame_size`), ensuring the OS guard page is
    /// triggered before any writes to the new stack region.
    ///
    /// For frames up to `PROBE_UNROLL_LIMIT` pages the probe is unrolled.
    /// For larger frames a counted loop using RAX is emitted.
    ///
    /// Returns an empty vector if the frame does not require probing.
    pub fn generate_stack_probe(&self, frame_size: u32) -> Vec<u8> {
        if !self.needs_stack_probe(frame_size) {
            return Vec::new();
        }

        let pages = frame_size / PAGE_SIZE;
        let remainder = frame_size % PAGE_SIZE;

        if pages <= PROBE_UNROLL_LIMIT {
            self.encode_unrolled_probe(pages, remainder)
        } else {
            self.encode_loop_probe(frame_size)
        }
    }

    /// Generate a stack probe as a sequence of [`MachineInstr`] values.
    ///
    /// This is the instruction-level equivalent of [`generate_stack_probe`],
    /// producing abstract machine instructions that integrate with the
    /// instruction selection pipeline rather than raw bytes.
    ///
    /// For frames up to `PROBE_UNROLL_LIMIT` pages the probe is unrolled.
    /// For larger frames a counted loop using RAX as a page counter is emitted.
    ///
    /// Returns an empty vector if the frame does not require probing.
    pub fn generate_stack_probe_instrs(&self, frame_size: u32) -> Vec<MachineInstr> {
        if !self.needs_stack_probe(frame_size) {
            return Vec::new();
        }

        let pages = frame_size / PAGE_SIZE;
        let remainder = frame_size % PAGE_SIZE;

        if pages <= PROBE_UNROLL_LIMIT {
            self.generate_unrolled_probe_instrs(pages, remainder)
        } else {
            self.generate_loop_probe_instrs(pages, remainder)
        }
    }

    // ========================================================================
    // Integration API
    // ========================================================================

    /// Apply all enabled security hardening features to a function's machine
    /// code byte stream.
    ///
    /// This is the high-level entry point called by the x86-64 backend after
    /// instruction selection and encoding. It applies, in order:
    ///
    /// 1. **CET `endbr64`** at function entry (if `cf_protection` is enabled
    ///    and `is_function_entry` is `true`).
    /// 2. **Stack probing** for large frames (if `frame_size` exceeds the
    ///    configured threshold).
    /// 3. **Retpoline** note: retpoline replacement operates at the
    ///    [`MachineInstr`] level via [`apply_retpoline`] before encoding.
    ///    The `has_indirect_branches` flag is informational here.
    ///
    /// # Parameters
    ///
    /// - `code`: The function's raw machine code bytes (modified in place).
    /// - `frame_size`: Total stack frame size in bytes.
    /// - `is_function_entry`: Whether this code represents a function entry.
    /// - `has_indirect_branches`: Whether the function contains indirect
    ///   call/jump instructions (informational; retpoline is applied at the
    ///   MachineInstr level).
    pub fn apply_security_hardening(
        &self,
        code: &mut Vec<u8>,
        frame_size: u32,
        is_function_entry: bool,
        _has_indirect_branches: bool,
    ) {
        // 1. Insert endbr64 at function entry if CET is enabled.
        if self.config.cf_protection && is_function_entry {
            self.insert_endbr64_at_function_entry(code);
        }

        // 2. Insert stack probe if frame exceeds threshold.
        if self.needs_stack_probe(frame_size) {
            let probe_bytes = self.generate_stack_probe(frame_size);
            // Insert probe after any endbr64 that was just prepended.
            let insert_pos = if self.config.cf_protection && is_function_entry {
                4 // After the 4-byte endbr64
            } else {
                0
            };
            code.splice(insert_pos..insert_pos, probe_bytes.iter().copied());
        }

        // 3. Retpoline replacement is handled at the MachineInstr level
        //    (apply_retpoline) before this function is called. The raw byte
        //    stream already contains direct calls to retpoline thunk symbols.
    }

    /// Returns additional `.text` sections containing retpoline thunk code.
    ///
    /// These sections should be appended to the object code by the backend's
    /// top-level code generation module. Each retpoline thunk gets its own
    /// section so the linker can deduplicate identical thunks across
    /// compilation units if desired.
    ///
    /// Returns an empty vector if retpoline is not enabled.
    pub fn get_retpoline_sections(&self) -> Vec<Section> {
        if !self.config.retpoline {
            return Vec::new();
        }

        let thunks = self.generate_retpoline_thunks();
        thunks
            .into_iter()
            .map(|thunk| Section {
                name: format!(".text.{}", thunk.name),
                data: thunk.code,
                section_type: SectionType::Text,
                alignment: 16,
                flags: SectionFlags {
                    writable: false,
                    executable: true,
                    allocatable: true,
                },
            })
            .collect()
    }

    // ========================================================================
    // Private helpers — unrolled stack probe (raw bytes)
    // ========================================================================

    /// Encode an unrolled stack probe sequence as raw machine code bytes.
    ///
    /// Emits one `sub rsp, 4096` + `test [rsp], rsp` pair per page,
    /// followed by a final `sub rsp, remainder` if non-zero.
    fn encode_unrolled_probe(&self, pages: u32, remainder: u32) -> Vec<u8> {
        let mut bytes = Vec::with_capacity((pages as usize) * 11 + 7);

        for _ in 0..pages {
            // sub rsp, 4096
            // REX.W(48) 81 EC imm32(00 10 00 00)
            bytes.extend_from_slice(&[0x48, 0x81, 0xEC]);
            bytes.extend_from_slice(&PAGE_SIZE.to_le_bytes());

            // test [rsp], rsp — touch the page (read probe)
            // REX.W(48) 85(TEST r/m64,r64) 24(ModR/M) 24(SIB)
            bytes.extend_from_slice(&[0x48, 0x85, 0x24, 0x24]);
        }

        // Final remainder adjustment (if non-zero).
        if remainder > 0 {
            // sub rsp, remainder
            bytes.extend_from_slice(&[0x48, 0x81, 0xEC]);
            bytes.extend_from_slice(&remainder.to_le_bytes());
        }

        bytes
    }

    /// Encode a loop-based stack probe as raw machine code bytes.
    ///
    /// Uses RAX as a temporary to hold the target RSP value. The loop
    /// decrements RSP by one page per iteration and probes each page
    /// until RSP reaches the target.
    ///
    /// ```text
    /// mov rax, rsp              ; save current RSP
    /// sub rax, <frame_size>     ; compute target = rsp - N
    /// .Lprobe_loop:
    ///     sub rsp, 4096         ; allocate one page
    ///     test [rsp], rsp       ; touch (probe) the new page
    ///     cmp rsp, rax          ; compare against target
    ///     ja .Lprobe_loop       ; loop while rsp > target
    /// mov rsp, rax              ; set final rsp to exact target
    /// ```
    fn encode_loop_probe(&self, frame_size: u32) -> Vec<u8> {
        let mut bytes = Vec::with_capacity(32);

        // mov rax, rsp — save current RSP to RAX.
        // REX.W(48) 89(MOV r/m64,r64) E0(mod=11 reg=RSP(4) r/m=RAX(0))
        bytes.extend_from_slice(&[0x48, 0x89, 0xE0]);

        // sub rax, frame_size — compute target RSP value.
        // REX.W(48) 2D(SUB RAX,imm32) imm32
        bytes.extend_from_slice(&[0x48, 0x2D]);
        bytes.extend_from_slice(&frame_size.to_le_bytes());

        // .Lprobe_loop: (byte offset of loop body start)
        let loop_start = bytes.len();

        // sub rsp, 4096 — allocate one page.
        bytes.extend_from_slice(&[0x48, 0x81, 0xEC]);
        bytes.extend_from_slice(&PAGE_SIZE.to_le_bytes());

        // test [rsp], rsp — probe the page.
        bytes.extend_from_slice(&[0x48, 0x85, 0x24, 0x24]);

        // cmp rsp, rax — compare current RSP against target.
        // REX.W(48) 39(CMP r/m64,r64) C4(mod=11 reg=RAX(0) r/m=RSP(4))
        bytes.extend_from_slice(&[0x48, 0x39, 0xC4]);

        // ja .Lprobe_loop — loop if RSP > target (unsigned above).
        // 77(JA rel8)  rel8 = loop_start - (current + 2)
        let ja_pos = bytes.len();
        let rel8 = (loop_start as i32) - (ja_pos as i32 + 2);
        bytes.push(0x77);
        bytes.push(rel8 as u8);

        // mov rsp, rax — set final RSP to exact target.
        // REX.W(48) 89(MOV r/m64,r64) C4(mod=11 reg=RAX(0) r/m=RSP(4))
        bytes.extend_from_slice(&[0x48, 0x89, 0xC4]);

        bytes
    }

    // ========================================================================
    // Private helpers — unrolled stack probe (MachineInstr)
    // ========================================================================

    /// Generate an unrolled stack probe as [`MachineInstr`] sequences.
    ///
    /// One SUB+TEST pair per page, with a final SUB for any remainder.
    fn generate_unrolled_probe_instrs(
        &self,
        pages: u32,
        remainder: u32,
    ) -> Vec<MachineInstr> {
        let mut instrs = Vec::with_capacity((pages as usize) * 2 + 1);

        for _ in 0..pages {
            // sub rsp, 4096
            instrs.push(MachineInstr::with_operands(
                opcodes::SUB_RI,
                vec![
                    MachineOperand::Register(RSP),
                    MachineOperand::Immediate(PAGE_SIZE as i64),
                ],
            ));

            // test [rsp], rsp — probe the page
            instrs.push(MachineInstr::with_operands(
                opcodes::TEST_RR,
                vec![
                    MachineOperand::Memory {
                        base: RSP,
                        offset: 0,
                    },
                    MachineOperand::Register(RSP),
                ],
            ));
        }

        // Final remainder adjustment.
        if remainder > 0 {
            instrs.push(MachineInstr::with_operands(
                opcodes::SUB_RI,
                vec![
                    MachineOperand::Register(RSP),
                    MachineOperand::Immediate(remainder as i64),
                ],
            ));
        }

        instrs
    }

    /// Generate a loop-based stack probe as [`MachineInstr`] sequences.
    ///
    /// Uses RAX as a temporary to hold the target RSP and a counted loop
    /// approach for frames exceeding the unroll threshold.
    ///
    /// Instruction sequence:
    /// ```text
    /// mov rax, rsp              ; save current rsp
    /// sub rax, total            ; compute target rsp
    /// loop:
    ///   sub rsp, 4096           ; allocate one page
    ///   test [rsp], rsp         ; probe
    ///   cmp rsp, rax            ; compare to target
    ///   ja loop                 ; loop while rsp > target
    /// mov rsp, rax              ; set final rsp
    /// ```
    fn generate_loop_probe_instrs(
        &self,
        pages: u32,
        remainder: u32,
    ) -> Vec<MachineInstr> {
        let mut instrs = Vec::with_capacity(8);
        let total = (pages as i64) * (PAGE_SIZE as i64) + (remainder as i64);

        // mov rax, rsp — save current RSP to compute target.
        instrs.push(MachineInstr::with_operands(
            opcodes::MOV_RR,
            vec![
                MachineOperand::Register(RAX),
                MachineOperand::Register(RSP),
            ],
        ));

        // sub rax, total — compute target RSP value.
        instrs.push(MachineInstr::with_operands(
            opcodes::SUB_RI,
            vec![
                MachineOperand::Register(RAX),
                MachineOperand::Immediate(total),
            ],
        ));

        // Loop body start — the JCC below references this label.

        // sub rsp, 4096 — allocate one page.
        instrs.push(MachineInstr::with_operands(
            opcodes::SUB_RI,
            vec![
                MachineOperand::Register(RSP),
                MachineOperand::Immediate(PAGE_SIZE as i64),
            ],
        ));

        // test [rsp], rsp — probe the page.
        instrs.push(MachineInstr::with_operands(
            opcodes::TEST_RR,
            vec![
                MachineOperand::Memory {
                    base: RSP,
                    offset: 0,
                },
                MachineOperand::Register(RSP),
            ],
        ));

        // cmp rsp, <target> — compare current RSP against target in RAX.
        // Uses CMP_RI opcode with register operands; the encoder resolves
        // the correct encoding (CMP r/m64, r64) based on operand types.
        instrs.push(MachineInstr::with_operands(
            opcodes::CMP_RI,
            vec![
                MachineOperand::Register(RSP),
                MachineOperand::Register(RAX),
            ],
        ));

        // ja .Lprobe_loop — loop while RSP > target (CondCode::A).
        instrs.push(MachineInstr::with_operands(
            opcodes::JCC,
            vec![
                MachineOperand::Immediate(CondCode::A as i64),
                MachineOperand::Label(PROBE_LOOP_LABEL),
            ],
        ));

        // mov rsp, rax — set final RSP to the exact target value.
        instrs.push(MachineInstr::with_operands(
            opcodes::MOV_RR,
            vec![
                MachineOperand::Register(RSP),
                MachineOperand::Register(RAX),
            ],
        ));

        instrs
    }
}

// ============================================================================
// Standalone public function — encode_endbr64
// ============================================================================

/// Encode the `endbr64` instruction as raw bytes.
///
/// Returns the 4-byte encoding `[0xF3, 0x0F, 0x1E, 0xFA]` which marks a
/// valid indirect branch target for Intel CET (Control-flow Enforcement
/// Technology).
///
/// This is a standalone function so it can be used without instantiating
/// [`SecurityHardening`], e.g. during direct machine code emission.
pub fn encode_endbr64() -> [u8; 4] {
    [0xF3, 0x0F, 0x1E, 0xFA]
}

// ============================================================================
// Private helper functions
// ============================================================================

/// Encode a complete retpoline thunk for the given register.
///
/// The thunk sequence (17 bytes) is:
///
/// ```text
/// offset 0:  E8 07 00 00 00       call .Lsetup (rel32 = +7)
/// offset 5:  F3 90                pause
/// offset 7:  0F AE E8             lfence
/// offset 10: EB F9                jmp .Lcapture_spec (rel8 = -7)
/// offset 12: <mov %reg, (%rsp)>   4 bytes (REX.W + 89 + ModR/M + SIB)
/// offset 16: C3                   ret
/// ```
fn encode_retpoline_thunk(reg: PhysReg, name: &str) -> RetpolineThunk {
    let mut code = Vec::with_capacity(17);

    // call .Lsetup — E8 rel32
    // .Lsetup is at offset 12, call ends at offset 5, so rel32 = 12 - 5 = 7
    code.push(0xE8);
    code.extend_from_slice(&7_i32.to_le_bytes());

    // .Lcapture_spec: (offset 5)
    // pause — F3 90
    code.push(0xF3);
    code.push(0x90);

    // lfence — 0F AE E8
    code.push(0x0F);
    code.push(0xAE);
    code.push(0xE8);

    // jmp .Lcapture_spec — EB rel8
    // .Lcapture_spec is at offset 5, jmp ends at offset 12, so rel8 = 5 - 12 = -7
    code.push(0xEB);
    code.push((-7_i8) as u8);

    // .Lsetup: (offset 12)
    // mov %reg, (%rsp) — encode with REX.W prefix and correct register field
    let reg_idx = reg.0 as u8;
    encode_mov_reg_to_rsp_indirect(&mut code, reg_idx);

    // ret — C3
    code.push(0xC3);

    debug_assert_eq!(code.len(), 17, "retpoline thunk must be exactly 17 bytes");

    RetpolineThunk {
        name: name.to_string(),
        register: reg,
        code,
    }
}

/// Encode `mov %reg, (%rsp)` — stores the register value at the top of
/// the stack (the location where the `call` instruction pushed the return
/// address). This overwrites the return address so that `ret` jumps to
/// the actual indirect target register value.
///
/// # Encoding
///
/// For registers 0–7 (rax, rcx, rdx, rbx, rsp, rbp, rsi, rdi):
///   `REX.W(48)  89  ModR/M  SIB(24)`
///
/// For registers 8–15 (r8–r15):
///   `REX.W+REX.R(4C)  89  ModR/M  SIB(24)`
///
/// ModR/M = `(0b00 << 6) | ((reg & 0x07) << 3) | 0x04`
/// SIB    = `0x24` (base=RSP, no index)
fn encode_mov_reg_to_rsp_indirect(code: &mut Vec<u8>, reg_idx: u8) {
    // REX prefix: W=1 (64-bit operand), R=1 if reg >= 8 (extended register)
    let rex = if reg_idx >= 8 { 0x4C } else { 0x48 };
    code.push(rex);

    // MOV r/m64, r64 opcode
    code.push(0x89);

    // ModR/M: mod=00 (indirect, no displacement), reg=lower 3 bits of
    // register index, r/m=100 (SIB byte follows for RSP addressing)
    let modrm = ((reg_idx & 0x07) << 3) | 0x04;
    code.push(modrm);

    // SIB: scale=00, index=100 (no index when index field = RSP),
    // base=100 (RSP)
    code.push(0x24);
}

/// Look up the retpoline thunk symbol name for a given physical register.
///
/// Returns `Some("__x86_retpoline_<name>")` if the register has a
/// corresponding thunk, or `None` if no thunk is available for that register.
fn retpoline_thunk_name_for_reg(reg: PhysReg) -> Option<String> {
    for &(thunk_reg, name) in &RETPOLINE_REGS {
        if reg == thunk_reg {
            return Some(format!("__x86_retpoline_{}", name));
        }
    }
    None
}

/// Map a condition code enum variant to a descriptive string (for
/// diagnostics and internal error messages only).
#[allow(dead_code)]
fn cond_code_name(cc: CondCode) -> &'static str {
    match cc {
        CondCode::A => "a",
        CondCode::AE => "ae",
        CondCode::B => "b",
        CondCode::BE => "be",
        CondCode::E => "e",
        CondCode::NE => "ne",
        CondCode::G => "g",
        CondCode::GE => "ge",
        CondCode::L => "l",
        CondCode::LE => "le",
        CondCode::S => "s",
        CondCode::NS => "ns",
        CondCode::P => "p",
        CondCode::NP => "np",
    }
}

/// Construct a [`CodeGenError::InternalError`] for security module failures.
///
/// This is a convenience function used within the security module for error
/// reporting. The error message is prefixed with "security hardening: " for
/// easy identification in diagnostic output.
#[allow(dead_code)]
fn security_error(msg: &str) -> CodeGenError {
    CodeGenError::InternalError(format!("security hardening: {}", msg))
}

// ============================================================================
// Unit tests
// ============================================================================

#[cfg(test)]
mod tests {
    use super::*;

    // ====================================================================
    // SecurityConfig tests
    // ====================================================================

    #[test]
    fn test_default_config() {
        let config = SecurityConfig::default();
        assert!(!config.retpoline, "retpoline should be disabled by default");
        assert!(
            !config.cf_protection,
            "cf_protection should be disabled by default"
        );
        assert_eq!(
            config.stack_probe_threshold, 4096,
            "stack probe threshold should default to 4096"
        );
    }

    #[test]
    fn test_from_flags() {
        let config = SecurityConfig::from_flags(true, false);
        assert!(config.retpoline);
        assert!(!config.cf_protection);
        assert_eq!(config.stack_probe_threshold, 4096);

        let config2 = SecurityConfig::from_flags(false, true);
        assert!(!config2.retpoline);
        assert!(config2.cf_protection);

        let config3 = SecurityConfig::from_flags(true, true);
        assert!(config3.retpoline);
        assert!(config3.cf_protection);
    }

    // ====================================================================
    // Retpoline thunk encoding tests
    // ====================================================================

    #[test]
    fn test_retpoline_thunk_encoding() {
        let config = SecurityConfig::from_flags(true, false);
        let hardening = SecurityHardening::new(config);
        let thunks = hardening.generate_retpoline_thunks();

        // Should generate 4 thunks (RAX, RCX, RDX, R11).
        assert_eq!(thunks.len(), 4);

        // Verify the RAX thunk encoding byte-by-byte.
        let rax_thunk = &thunks[0];
        assert_eq!(rax_thunk.name, "__x86_retpoline_rax");
        assert_eq!(rax_thunk.register, RAX);
        assert_eq!(rax_thunk.code.len(), 17);

        let code = &rax_thunk.code;

        // Byte 0..5: call .Lsetup (E8 07 00 00 00)
        assert_eq!(code[0], 0xE8, "call opcode");
        assert_eq!(&code[1..5], &[0x07, 0x00, 0x00, 0x00], "call rel32 = +7");

        // Byte 5..7: pause (F3 90)
        assert_eq!(code[5], 0xF3, "pause prefix");
        assert_eq!(code[6], 0x90, "pause opcode");

        // Byte 7..10: lfence (0F AE E8)
        assert_eq!(code[7], 0x0F, "lfence byte 1");
        assert_eq!(code[8], 0xAE, "lfence byte 2");
        assert_eq!(code[9], 0xE8, "lfence byte 3");

        // Byte 10..12: jmp .Lcapture_spec (EB F9)
        assert_eq!(code[10], 0xEB, "jmp rel8 opcode");
        assert_eq!(code[11], 0xF9, "jmp rel8 = -7");

        // Byte 12..16: mov %rax, (%rsp) (48 89 04 24)
        assert_eq!(code[12], 0x48, "REX.W for rax");
        assert_eq!(code[13], 0x89, "MOV r/m64, r64");
        assert_eq!(code[14], 0x04, "ModR/M: rax, [SIB]");
        assert_eq!(code[15], 0x24, "SIB: base=RSP");

        // Byte 16: ret (C3)
        assert_eq!(code[16], 0xC3, "ret");
    }

    #[test]
    fn test_retpoline_thunk_r11_encoding() {
        let config = SecurityConfig::from_flags(true, false);
        let hardening = SecurityHardening::new(config);
        let thunks = hardening.generate_retpoline_thunks();

        // R11 thunk is the 4th one (index 3).
        let r11_thunk = &thunks[3];
        assert_eq!(r11_thunk.name, "__x86_retpoline_r11");
        assert_eq!(r11_thunk.register, R11);
        assert_eq!(r11_thunk.code.len(), 17);

        let code = &r11_thunk.code;

        // The mov %r11, (%rsp) encoding: R11 is register 11 (1011b).
        // REX = 0x4C (W=1, R=1 for extended register)
        // ModR/M: reg = 011 (lower 3 bits of 11), r/m = 100 (SIB)
        //   = (011 << 3) | 100 = 0x1C
        assert_eq!(code[12], 0x4C, "REX.W+REX.R for r11");
        assert_eq!(code[13], 0x89, "MOV r/m64, r64");
        assert_eq!(code[14], 0x1C, "ModR/M: r11, [SIB]");
        assert_eq!(code[15], 0x24, "SIB: base=RSP");
    }

    #[test]
    fn test_retpoline_thunk_names() {
        let config = SecurityConfig::from_flags(true, false);
        let hardening = SecurityHardening::new(config);
        let thunks = hardening.generate_retpoline_thunks();

        let names: Vec<&str> = thunks.iter().map(|t| t.name.as_str()).collect();
        assert_eq!(
            names,
            vec![
                "__x86_retpoline_rax",
                "__x86_retpoline_rcx",
                "__x86_retpoline_rdx",
                "__x86_retpoline_r11",
            ]
        );
    }

    #[test]
    fn test_needs_retpoline() {
        let config = SecurityConfig::from_flags(true, false);
        let hardening = SecurityHardening::new(config);

        // An indirect call through RAX should need retpoline.
        let indirect_call = MachineInstr::with_operands(
            opcodes::CALL_R,
            vec![MachineOperand::Register(RAX)],
        );
        assert!(hardening.needs_retpoline_replacement(&indirect_call));

        // A direct call should NOT need retpoline.
        let direct_call = MachineInstr::with_operands(
            opcodes::CALL,
            vec![MachineOperand::Symbol("foo".to_string())],
        );
        assert!(!hardening.needs_retpoline_replacement(&direct_call));

        // A regular instruction should NOT need retpoline.
        let add_instr = MachineInstr::with_operands(
            opcodes::ADD_RR,
            vec![
                MachineOperand::Register(RAX),
                MachineOperand::Register(RCX),
            ],
        );
        assert!(!hardening.needs_retpoline_replacement(&add_instr));
    }

    #[test]
    fn test_retpoline_disabled() {
        let config = SecurityConfig::from_flags(false, false);
        let hardening = SecurityHardening::new(config);

        // With retpoline disabled, generate_retpoline_thunks returns empty.
        assert!(hardening.generate_retpoline_thunks().is_empty());

        // needs_retpoline_replacement always returns false.
        let indirect_call = MachineInstr::with_operands(
            opcodes::CALL_R,
            vec![MachineOperand::Register(RAX)],
        );
        assert!(!hardening.needs_retpoline_replacement(&indirect_call));

        // apply_retpoline does nothing.
        let mut instrs = vec![indirect_call];
        hardening.apply_retpoline(&mut instrs);
        assert_eq!(instrs[0].opcode, opcodes::CALL_R);
    }

    #[test]
    fn test_apply_retpoline() {
        let config = SecurityConfig::from_flags(true, false);
        let hardening = SecurityHardening::new(config);

        let mut instrs = vec![
            MachineInstr::with_operands(
                opcodes::CALL_R,
                vec![MachineOperand::Register(RAX)],
            ),
            MachineInstr::with_operands(
                opcodes::ADD_RR,
                vec![
                    MachineOperand::Register(RAX),
                    MachineOperand::Register(RCX),
                ],
            ),
            MachineInstr::with_operands(
                opcodes::CALL_R,
                vec![MachineOperand::Register(R11)],
            ),
        ];

        hardening.apply_retpoline(&mut instrs);

        // First instruction: CALL_R(RAX) → CALL(__x86_retpoline_rax)
        assert_eq!(instrs[0].opcode, opcodes::CALL);
        match &instrs[0].operands[0] {
            MachineOperand::Symbol(name) => {
                assert_eq!(name, "__x86_retpoline_rax");
            }
            _ => panic!("expected Symbol operand"),
        }

        // Second instruction: ADD unchanged.
        assert_eq!(instrs[1].opcode, opcodes::ADD_RR);

        // Third instruction: CALL_R(R11) → CALL(__x86_retpoline_r11)
        assert_eq!(instrs[2].opcode, opcodes::CALL);
        match &instrs[2].operands[0] {
            MachineOperand::Symbol(name) => {
                assert_eq!(name, "__x86_retpoline_r11");
            }
            _ => panic!("expected Symbol operand"),
        }
    }

    // ====================================================================
    // CET endbr64 tests
    // ====================================================================

    #[test]
    fn test_endbr64_encoding() {
        let bytes = encode_endbr64();
        assert_eq!(bytes, [0xF3, 0x0F, 0x1E, 0xFA]);
    }

    #[test]
    fn test_endbr64_insertion_at_function_entry() {
        let config = SecurityConfig::from_flags(false, true);
        let hardening = SecurityHardening::new(config);

        // Start with a small function body.
        let mut code: Vec<u8> = vec![0x55, 0x48, 0x89, 0xE5]; // push rbp; mov rbp, rsp

        hardening.insert_endbr64_at_function_entry(&mut code);

        // endbr64 should be prepended.
        assert_eq!(&code[0..4], &[0xF3, 0x0F, 0x1E, 0xFA]);
        // Original code follows.
        assert_eq!(&code[4..8], &[0x55, 0x48, 0x89, 0xE5]);
        assert_eq!(code.len(), 8);
    }

    #[test]
    fn test_cf_protection_disabled() {
        let config = SecurityConfig::from_flags(false, false);
        let hardening = SecurityHardening::new(config);

        let mut code: Vec<u8> = vec![0x55, 0x48, 0x89, 0xE5];
        let original = code.clone();

        hardening.insert_endbr64_at_function_entry(&mut code);

        // No modification when cf_protection is disabled.
        assert_eq!(code, original);
    }

    #[test]
    fn test_insert_endbr64_at_indirect_targets() {
        let config = SecurityConfig::from_flags(false, true);
        let hardening = SecurityHardening::new(config);

        let mut instrs = vec![
            MachineInstr::new(opcodes::NOP),    // index 0
            MachineInstr::new(opcodes::NOP),    // index 1
            MachineInstr::new(opcodes::NOP),    // index 2
        ];

        // Insert ENDBR64 at positions 0 and 2.
        hardening.insert_endbr64_at_indirect_targets(&mut instrs, &[0, 2]);

        // Should now have 5 instructions: ENDBR64 at 0, NOP, NOP, ENDBR64, NOP
        assert_eq!(instrs.len(), 5);
        assert_eq!(instrs[0].opcode, opcodes::ENDBR64);
        assert_eq!(instrs[1].opcode, opcodes::NOP);
        assert_eq!(instrs[2].opcode, opcodes::NOP);
        assert_eq!(instrs[3].opcode, opcodes::ENDBR64);
        assert_eq!(instrs[4].opcode, opcodes::NOP);
    }

    // ====================================================================
    // Stack probing tests
    // ====================================================================

    #[test]
    fn test_no_probe_for_small_frames() {
        let config = SecurityConfig::default();
        let hardening = SecurityHardening::new(config);

        assert!(!hardening.needs_stack_probe(0));
        assert!(!hardening.needs_stack_probe(1024));
        assert!(!hardening.needs_stack_probe(4096));
        assert!(hardening.needs_stack_probe(4097));
    }

    #[test]
    fn test_probe_for_large_frame() {
        let config = SecurityConfig::default();
        let hardening = SecurityHardening::new(config);

        assert!(hardening.needs_stack_probe(8192));

        let bytes = hardening.generate_stack_probe(8192);
        assert!(!bytes.is_empty());

        // 8192 = 2 pages, 0 remainder → 2 × (sub 7 + test 4) = 22 bytes
        assert_eq!(bytes.len(), 22);

        // Check that each page probe starts with sub rsp, 4096 (48 81 EC 00 10 00 00).
        assert_eq!(&bytes[0..3], &[0x48, 0x81, 0xEC]);
        assert_eq!(&bytes[3..7], &PAGE_SIZE.to_le_bytes());
        // Followed by test [rsp], rsp (48 85 24 24).
        assert_eq!(&bytes[7..11], &[0x48, 0x85, 0x24, 0x24]);

        // Second probe.
        assert_eq!(&bytes[11..14], &[0x48, 0x81, 0xEC]);
        assert_eq!(&bytes[14..18], &PAGE_SIZE.to_le_bytes());
        assert_eq!(&bytes[18..22], &[0x48, 0x85, 0x24, 0x24]);
    }

    #[test]
    fn test_probe_with_remainder() {
        let config = SecurityConfig::default();
        let hardening = SecurityHardening::new(config);

        // 5000 = 1 page + 904 remainder
        let bytes = hardening.generate_stack_probe(5000);
        assert!(!bytes.is_empty());

        // 1 × (sub 7 + test 4) + sub_remainder 7 = 18 bytes
        assert_eq!(bytes.len(), 18);

        // First page probe.
        assert_eq!(&bytes[0..3], &[0x48, 0x81, 0xEC]);
        assert_eq!(&bytes[3..7], &PAGE_SIZE.to_le_bytes());
        assert_eq!(&bytes[7..11], &[0x48, 0x85, 0x24, 0x24]);

        // Remainder: sub rsp, 904 (= 0x0388)
        assert_eq!(&bytes[11..14], &[0x48, 0x81, 0xEC]);
        let remainder: u32 = 5000 - 4096;
        assert_eq!(&bytes[14..18], &remainder.to_le_bytes());
    }

    #[test]
    fn test_probe_loop_for_very_large_frame() {
        let config = SecurityConfig::default();
        let hardening = SecurityHardening::new(config);

        // 65536 = 16 pages → exceeds unroll limit (8), uses loop.
        let bytes = hardening.generate_stack_probe(65536);
        assert!(!bytes.is_empty());

        // Loop probe structure:
        // mov rax, rsp (3) + sub rax, N (6) + loop body (16) + mov rsp, rax (3) = 28
        assert_eq!(bytes.len(), 28);

        // First 3 bytes: mov rax, rsp (48 89 E0)
        assert_eq!(&bytes[0..3], &[0x48, 0x89, 0xE0]);

        // Next 6 bytes: sub rax, 65536 (48 2D 00 00 01 00)
        assert_eq!(&bytes[3..5], &[0x48, 0x2D]);
        assert_eq!(&bytes[5..9], &65536_u32.to_le_bytes());

        // Loop body includes sub rsp, test, cmp, ja
        // sub rsp, 4096 at offset 9
        assert_eq!(&bytes[9..12], &[0x48, 0x81, 0xEC]);

        // ret (last byte) = mov rsp, rax (48 89 C4)
        assert_eq!(&bytes[25..28], &[0x48, 0x89, 0xC4]);
    }

    #[test]
    fn test_probe_touches_every_page() {
        let config = SecurityConfig::default();
        let hardening = SecurityHardening::new(config);

        // Test with 4 pages (16384 bytes).
        let bytes = hardening.generate_stack_probe(16384);

        // Should be unrolled: 4 × (sub 7 + test 4) = 44 bytes.
        assert_eq!(bytes.len(), 44);

        // Count the number of test [rsp], rsp sequences (48 85 24 24).
        let test_pattern = [0x48_u8, 0x85, 0x24, 0x24];
        let test_count = bytes
            .windows(4)
            .filter(|w| *w == test_pattern)
            .count();
        assert_eq!(
            test_count, 4,
            "must probe exactly 4 pages for 16384-byte frame"
        );

        // Count the number of sub rsp, 4096 sequences.
        let sub_prefix = [0x48_u8, 0x81, 0xEC];
        let sub_count = bytes
            .windows(7)
            .filter(|w| w[0..3] == sub_prefix && w[3..7] == PAGE_SIZE.to_le_bytes())
            .count();
        assert_eq!(
            sub_count, 4,
            "must subtract 4096 exactly 4 times for 16384-byte frame"
        );
    }

    #[test]
    fn test_probe_instrs_unrolled() {
        let config = SecurityConfig::default();
        let hardening = SecurityHardening::new(config);

        // 8192 = 2 pages → 2 × (SUB + TEST) = 4 instructions.
        let instrs = hardening.generate_stack_probe_instrs(8192);
        assert_eq!(instrs.len(), 4);

        // First pair: SUB_RI, TEST_RR
        assert_eq!(instrs[0].opcode, opcodes::SUB_RI);
        assert_eq!(instrs[1].opcode, opcodes::TEST_RR);
        // Second pair.
        assert_eq!(instrs[2].opcode, opcodes::SUB_RI);
        assert_eq!(instrs[3].opcode, opcodes::TEST_RR);
    }

    #[test]
    fn test_probe_instrs_loop() {
        let config = SecurityConfig::default();
        let hardening = SecurityHardening::new(config);

        // 65536 = 16 pages → loop probe.
        let instrs = hardening.generate_stack_probe_instrs(65536);

        // Loop probe: MOV_RR, SUB_RI, SUB_RI, TEST_RR, CMP_RI, JCC, MOV_RR
        assert_eq!(instrs.len(), 7);
        assert_eq!(instrs[0].opcode, opcodes::MOV_RR);
        assert_eq!(instrs[1].opcode, opcodes::SUB_RI);
        assert_eq!(instrs[2].opcode, opcodes::SUB_RI);
        assert_eq!(instrs[3].opcode, opcodes::TEST_RR);
        assert_eq!(instrs[4].opcode, opcodes::CMP_RI);
        assert_eq!(instrs[5].opcode, opcodes::JCC);
        assert_eq!(instrs[6].opcode, opcodes::MOV_RR);

        // Verify JCC condition code is CondCode::A
        match &instrs[5].operands[0] {
            MachineOperand::Immediate(val) => {
                assert_eq!(*val, CondCode::A as i64);
            }
            _ => panic!("expected Immediate operand for JCC condition code"),
        }
    }

    #[test]
    fn test_no_probe_returns_empty() {
        let config = SecurityConfig::default();
        let hardening = SecurityHardening::new(config);

        assert!(hardening.generate_stack_probe(0).is_empty());
        assert!(hardening.generate_stack_probe(2048).is_empty());
        assert!(hardening.generate_stack_probe(4096).is_empty());

        assert!(hardening.generate_stack_probe_instrs(0).is_empty());
        assert!(hardening.generate_stack_probe_instrs(2048).is_empty());
        assert!(hardening.generate_stack_probe_instrs(4096).is_empty());
    }

    // ====================================================================
    // Integration tests
    // ====================================================================

    #[test]
    fn test_apply_security_hardening_all_features() {
        let config = SecurityConfig {
            retpoline: true,
            cf_protection: true,
            stack_probe_threshold: 4096,
        };
        let hardening = SecurityHardening::new(config);

        // Start with a small function body.
        let mut code: Vec<u8> = vec![0x55, 0x48, 0x89, 0xE5]; // push rbp; mov rbp, rsp

        hardening.apply_security_hardening(
            &mut code,
            8192,  // > 4096, needs probe
            true,  // function entry
            true,  // has indirect branches (informational)
        );

        // endbr64 should be at the start.
        assert_eq!(&code[0..4], &[0xF3, 0x0F, 0x1E, 0xFA]);

        // Stack probe should follow (2 pages = 22 bytes).
        // After endbr64 (4 bytes), probe starts at offset 4.
        // Total: 4 (endbr64) + 22 (probe) + 4 (original) = 30.
        assert_eq!(code.len(), 30);

        // Original code should be at the end.
        assert_eq!(&code[26..30], &[0x55, 0x48, 0x89, 0xE5]);
    }

    #[test]
    fn test_apply_security_hardening_no_features() {
        let config = SecurityConfig::default();
        let hardening = SecurityHardening::new(config);

        let mut code: Vec<u8> = vec![0x55, 0x48, 0x89, 0xE5];
        let original = code.clone();

        hardening.apply_security_hardening(&mut code, 1024, true, false);

        // No modifications when all features are disabled and frame is small.
        assert_eq!(code, original);
    }

    #[test]
    fn test_apply_security_hardening_only_probe() {
        let config = SecurityConfig::default();
        let hardening = SecurityHardening::new(config);

        let mut code: Vec<u8> = vec![0xC3]; // ret

        hardening.apply_security_hardening(&mut code, 8192, false, false);

        // Stack probe should be prepended (no endbr64 since not function entry).
        // 2 pages unrolled = 22 bytes, then original ret.
        assert_eq!(code.len(), 23);
        assert_eq!(code[22], 0xC3);
    }

    #[test]
    fn test_get_retpoline_sections() {
        let config = SecurityConfig::from_flags(true, false);
        let hardening = SecurityHardening::new(config);

        let sections = hardening.get_retpoline_sections();
        assert_eq!(sections.len(), 4);

        for section in &sections {
            assert!(section.name.starts_with(".text.__x86_retpoline_"));
            assert_eq!(section.section_type, SectionType::Text);
            assert_eq!(section.alignment, 16);
            assert!(section.flags.executable);
            assert!(section.flags.allocatable);
            assert!(!section.flags.writable);
            assert_eq!(section.data.len(), 17);
        }
    }

    #[test]
    fn test_get_retpoline_sections_disabled() {
        let config = SecurityConfig::from_flags(false, false);
        let hardening = SecurityHardening::new(config);

        let sections = hardening.get_retpoline_sections();
        assert!(sections.is_empty());
    }

    #[test]
    fn test_retpoline_thunk_rcx_encoding() {
        let config = SecurityConfig::from_flags(true, false);
        let hardening = SecurityHardening::new(config);
        let thunks = hardening.generate_retpoline_thunks();

        let rcx_thunk = &thunks[1];
        assert_eq!(rcx_thunk.register, RCX);

        // mov %rcx, (%rsp): 48 89 0C 24
        // RCX encoding = 1, ModR/M = (1 << 3) | 4 = 0x0C
        assert_eq!(rcx_thunk.code[12], 0x48);
        assert_eq!(rcx_thunk.code[13], 0x89);
        assert_eq!(rcx_thunk.code[14], 0x0C);
        assert_eq!(rcx_thunk.code[15], 0x24);
    }

    #[test]
    fn test_retpoline_thunk_rdx_encoding() {
        let config = SecurityConfig::from_flags(true, false);
        let hardening = SecurityHardening::new(config);
        let thunks = hardening.generate_retpoline_thunks();

        let rdx_thunk = &thunks[2];
        assert_eq!(rdx_thunk.register, RDX);

        // mov %rdx, (%rsp): 48 89 14 24
        // RDX encoding = 2, ModR/M = (2 << 3) | 4 = 0x14
        assert_eq!(rdx_thunk.code[12], 0x48);
        assert_eq!(rdx_thunk.code[13], 0x89);
        assert_eq!(rdx_thunk.code[14], 0x14);
        assert_eq!(rdx_thunk.code[15], 0x24);
    }

    #[test]
    fn test_security_error_helper() {
        let err = security_error("test failure");
        match err {
            CodeGenError::InternalError(msg) => {
                assert!(msg.contains("security hardening"));
                assert!(msg.contains("test failure"));
            }
            _ => panic!("expected InternalError"),
        }
    }

    #[test]
    fn test_retpoline_thunk_name_for_known_regs() {
        assert_eq!(
            retpoline_thunk_name_for_reg(RAX),
            Some("__x86_retpoline_rax".to_string())
        );
        assert_eq!(
            retpoline_thunk_name_for_reg(RCX),
            Some("__x86_retpoline_rcx".to_string())
        );
        assert_eq!(
            retpoline_thunk_name_for_reg(RDX),
            Some("__x86_retpoline_rdx".to_string())
        );
        assert_eq!(
            retpoline_thunk_name_for_reg(R11),
            Some("__x86_retpoline_r11".to_string())
        );
    }

    #[test]
    fn test_retpoline_thunk_name_for_unknown_reg() {
        // RSP should not have a retpoline thunk.
        assert_eq!(retpoline_thunk_name_for_reg(RSP), None);
        // R15 should not have one either.
        assert_eq!(retpoline_thunk_name_for_reg(PhysReg(15)), None);
    }

    #[test]
    fn test_cond_code_name() {
        assert_eq!(cond_code_name(CondCode::A), "a");
        assert_eq!(cond_code_name(CondCode::E), "e");
        assert_eq!(cond_code_name(CondCode::NE), "ne");
    }

    #[test]
    fn test_loop_probe_bytes_ja_target() {
        let config = SecurityConfig::default();
        let hardening = SecurityHardening::new(config);

        // 40960 = 10 pages → loop probe (exceeds unroll limit of 8).
        let bytes = hardening.generate_stack_probe(40960);

        // Verify the JA instruction's relative offset targets the loop start.
        // Structure: mov(3) + sub(6) + [loop: sub(7) + test(4) + cmp(3) + ja(2)]
        //           + mov(3) = 28 bytes total.
        // Loop start offset = 9.
        // JA is at offset 23 (9 + 7 + 4 + 3 = 23).
        // JA occupies 2 bytes (77 rel8), ends at offset 25.
        // rel8 = 9 - 25 = -16 = 0xF0.
        assert_eq!(bytes[23], 0x77, "JA opcode");
        assert_eq!(bytes[24], 0xF0, "JA rel8 = -16 (back to loop start)");
    }
}
